from abc import ABC, abstractmethod
from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
import pandas as pd


class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class StrategySignal(BaseModel):
    """
    Structured signal generated by a trading strategy.
    """
    signal: SignalType
    timestamp: str
    symbol: str
    reason: str
    indicators: Dict[str, Optional[float]] = Field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.
    Decoupled from HTTP, database, and UI layers.
    """

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, symbol: str) -> StrategySignal:
        """
        Evaluates the latest available candle in df and returns a structured signal.
        """
        pass

    @abstractmethod
    def generate_all_signals(self, df: pd.DataFrame, symbol: str) -> pd.DataFrame:
        """
        Generates signals across the entire historical DataFrame for backtesting.
        Appends a 'signal' column with values 'BUY', 'SELL', 'HOLD'.
        """
        pass

    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """Returns the configurable parameters of the strategy."""
        pass
